@extends('layouts.master')

{{-- Page title --}}
@section('title')
    Terms of Service
    @parent
    @stop

@section('page_styles')

@stop
@section('top')
    <img style="width:100%;" src="https://hobo-assets.s3-us-west-2.amazonaws.com/images/gourley/rod-rack.jpg">
@stop

@section('content')
    <div class="container col-md-6 col-md-offset-3">
    <h1>TERMS OF SERVICE</h1>
        <h3>Hobo Fly Fishing  terms of sale</h3>
        <p>Many destinations that we offer here at Hobo Fly Fishing offer fly fishing travel packages that are non-refundable. We highly recommend travel insurance for this reason.</p>
        <p>We do our best to provide complete and accurate information, but this is not always within our control. We cannot be held liable for force majeure or the actions of
            external entities, but we always do our level best to take care of our customers within our power.</p>
        <p>Most packages will  typically consist of  a 50 percent total package price per angler with the balance due 90 days in advance prior to the arrival date.
            Some packages may require full payment for the entire package.
        </p>
        <h3>hoboflyfishing.com - SAAS TERMS OF SERVICE</h3>
        <p>IMPORTANT: THIS AGREEMENT IS A LEGALLY BINDING AGREEMENT BETWEEN YOU AND Hobo Fly Fishing APPLICABLE TO YOUR
            PURCHASE AND/OR USE (INCLUDING FREE, “EVALUATION” AND/OR “TRIAL” USES) OF Hobo Fly Fishing's SAAS PRODUCTS
            AND/OR Hobo Fly Fishing's SYSTEM.  BY USING OUR SAAS YOU AGREE TO BE BOUND BY THE TERMS OF THIS AGREEMENT.
            IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF THIS AGREEMENT YOU MAY NOT USE ANY Hobo Fly Fishing SAAS
            PRODUCT NOR ACCESS THE SYSTEM.</p>
        <p>This Terms of Service Agreement (&quot;Agreement&quot;) is by and between Hobo Fly Fishing 
            (including its wholly-owned subsidiaries, licensors, and affiliates, collectively referred to as; “Hobo Fly Fishing”)
            and the person or entity executing this Agreement (referred to herein as “You” or “Customer”). The terms “You”
            , “Your”,  and “Customer” include you and any of your owners, employees, partners, independent contractors,
            subsidiaries, affiliates, attorneys, agents, heirs, and assigns.  This Agreement is effective as a pre-requisite
            for accessing our system, this includes but is not limited to all services hosted at the domain hoboflyfishing.com.
            Your use of and Hobo Fly Fishing’s provision of any SaaS product and access to Hobo Fly Fishing's System (as
            those terms are hereinafter defined) are governed by this Agreement.</p>
        <p>This Agreement, together with Hobo Fly Fishing’s End User License Agreement (where applicable), sets out the
            terms that apply to the use of all Hobo Fly Fishing “software as a service” (“SaaS”) products.
            SaaS consists generally of system administration, system management, and system monitoring activities that
            Hobo Fly Fishing performs for Hobo Fly Fishing programs, and includes the right to use the Hobo Fly Fishing
            programs, support services for such Hobo Fly Fishing programs, and other services provided by Hobo Fly Fishing.</p>
        <ol>
            <li>
                <p>DEFINITIONS. The following capitalized terms shall have the following meanings whenever used in this Agreement.
                    1.1. “Aggregate Data” refers to Customer Data with the following information removed: personally identifiable information, the names and addresses of the Customer, and player names, table names and game numbers.
                    1.2. “AUP” means Hobo Fly Fishing’s acceptable use policy, as the same is subject to change from time to time in Hobo Fly Fishing’s sole discretion.
                    1.3. “Confidential Information” is defined in Section 7.
                    1.4. “Customer Data” means data in electronic form input or collected through the System by or from Customer.
                    1.5. “Documentation” means materials and/or manuals and instructions provided by Hobo Fly Fishing which are related to use of its System and/or SaaS products, as the same may be amended, replaced and/or supplemented from time to time.
                    1.6. “Excluded Data” is defined in Section 4.6 below.
                    1.7. “Feedback” means any Customer suggestion, comment, or idea, in any medium, for improving, correcting, or otherwise modifying any of Hobo Fly Fishing’s products or services, whether part of the System or otherwise.
                    1.8. “Hobo Fly Fishing Associates” means Hobo Fly Fishing’s officers, directors, shareholders, parents, subsidiaries, agents, successors, and assigns.
                    1.9. “Hobo Fly Fishing Programs” means the software products owned or distributed by Hobo Fly Fishing to which Hobo Fly Fishing grants you access as part of the SaaS products, including program documentation and any program updates.   SaaS products provided by Hobo Fly Fishing may include but is not limited to the Hobo Fly Fishing Programs known as  “hoboflyfishing.com” and all updates, improvements, modifications, patches, and corrections, made or provided with respect to the same.  In certain instances, both this Agreement and Hobo Fly Fishing's End User License Agreement may be applicable to Your purchase and/or use of SaaS products.
                    1.10. “Order” means an order for a SaaS product and/or access to the System (or, in the case of a free or trial period, a request to access the System), for the stated time period identified when the purchase was made or access was requested.  Hobo Fly Fishing reserves the right to reject any Order at any time for any reason whatsoever.
                    1.11. “Privacy Policy” means Hobo Fly Fishing’s privacy policy, currently posted at Privacy Policy .
                    1.12. “SLA” means the relevant Hobo Fly Fishing standard service level agreement(s) for its products and services, to the extent the same are offered and/or published.  SLAs for individual SaaS products may each be different from the others and may be modified by Hobo Fly Fishing from time to time.
                    1.13. “Subscription Fee” means the cost for access to a SaaS product and access to the System for the period paid for.
                    1.14. “System” means, generally, the computer servers, Hobo Fly Fishing Programs, and methods by which Hobo Fly Fishing provides SaaS products to its customers.
                    1.15. “Term”  The term of this Agreement (“Term”) commences on the Effective Date and continues for the period set forth in the Order (as the same may be automatically renewed from time to time as set forth in Your Order) or until this Agreement is terminated by either party.</p>
            </li>
            <li>THE SYSTEM.
                2.1. Use of the System. During the Term, Customer shall have the nonexclusive right to access and use the System pursuant to: (a) the terms of any outstanding Order, including such features and functions as the Order requires; and (b) Hobo Fly Fishing’s policies makes available on its websites from time to time, as such policies may be amended, updated and/or modified from time to time.
                2.2.  You acknowledge that Hobo Fly Fishing has no Hobo Fly Fishing Program delivery obligation and will not ship copies of the Hobo Fly Fishing Programs to you as part of the SaaS product ordered. You agree that You do not acquire under this Agreement any license to use the Hobo Fly Fishing Programs specified in the Order in excess of the scope and/or duration of the Order.  Upon the end of this Agreement, Your right to access or use the Hobo Fly Fishing Programs specified in the Order and the services shall terminate.
                2.3. Service Levels. Hobo Fly Fishing shall provide the remedies listed in the SLA for any failure of the System listed in the SLA. Such remedies are Customer’s sole remedy for any failure of the System, and Customer recognizes and agrees that if the SLA does not list a remedy for a given failure, it has no remedy. Credits issued pursuant to the SLA apply to outstanding or future invoices only and are forfeited upon termination of this Agreement. Hobo Fly Fishing is not required to issue refunds or to make payments against such credits under any circumstances, including without limitation after termination of this Agreement.
                2.4. Documentation. You may use and reproduce the Documentation solely as necessary to support your use of the System.
                2.5. System Revisions. Hobo Fly Fishing may revise System features and functions or the SLA at any time, including without limitation by removing such features and functions or reducing service levels. If any such revision to the System materially reduces features or functionality provided pursuant to an Order, You may within 30 days of the date of the revision terminate such Order, without cause, or terminate this Agreement without cause if such Order is the only one outstanding.
                2.6. Other Hobo Fly Fishing Programs and Products.  Your purchase of SaaS products and/or access to and use of the System may be contingent on your purchase of other products and/or services sold or provided by Hobo Fly Fishing which are not SaaS products. Use of Hobo Fly Fishing products which are not SaaS products (i.e., software products which are not provided by subscription and/or are not provided as “software as a service”) requires agreement with Hobo Fly Fishing’s End-User License Agreement (available at: End User License Agreement) prior to the time such Hobo Fly Fishing products are purchased and/or accessed.</li>
        </ol>
        <p>3.FEES. You agree to pay Hobo Fly Fishing the Subscription Fee set forth in each Order for each SaaS product,
            for each Term. Payment of the Subscription Fee will entitle you to access to the SaaS product or service ordered
            only for the time period identified at the time of your Order.  Hobo Fly Fishing will not be required to refund
            any portion of a Subscription Fee under any circumstances whatsoever. This provision does not apply to free accounts
            which have limited access to our Services.</p>
        <p>4.CUSTOMER DATA AND PRIVACY.
            4.1. Use of Customer Data. Unless it receives your prior written consent, Hobo Fly Fishing: (a) shall not access, process, or otherwise use Customer Data other than as necessary to facilitate the System and Your use of SaaS products; and (b) shall not intentionally grant any third party access to Customer Data, including without limitation Hobo Fly Fishing’s other customers, except Hobo Fly Fishing’s subcontractors and vendors that are subject to a reasonable nondisclosure agreement. Notwithstanding the foregoing, Hobo Fly Fishing may disclose Customer Data as required by applicable law or by proper legal or governmental authority. Hobo Fly Fishing shall give endeavor to give You prompt notice of any such legal or governmental demand and reasonably cooperate with You in any effort to seek a protective order or otherwise to contest such required disclosure, at Your expense.
            4.2. Privacy Policy. The Privacy Policy does not apply to any third party website or service linked to the System or recommended or referred to through the System or by Hobo Fly Fishing.
            4.3. Risk of Exposure. You recognize and agree that hosting data online involves known and unknown risks of unauthorized disclosure or exposure and that, in accessing and using the System, You assume such risks.  Hobo Fly Fishing will make reasonable efforts to keep all Customer Data from unauthorized disclosure but Hobo Fly Fishing does not offer any representation, warranty, or guarantee that Customer Data will not be exposed or disclosed through errors or the actions of third parties.
            4.4. Data Accuracy. Hobo Fly Fishing shall have no responsibility or liability for the accuracy of data uploaded to the System or utilized during the course of using a SaaS product or service by You, including without limitation Customer Data and any other data uploaded by Users.
            4.5. Data Deletion. Hobo Fly Fishing may permanently erase Customer Data if Your account is delinquent, suspended, or terminated.  Hobo Fly Fishing shall have no obligation to maintain any Customer Data except during the Term (as such obligation is otherwise limited in this Agreement). You agree and acknowledge that Hobo Fly Fishing has no obligation to retain Your data and that Your data may be irretrievably deleted at the end of the Term.
            4.6. Excluded Data. You represent and warrant that Customer Data does not and will not include, and You have not and shall not upload or transmit to Hobo Fly Fishing's System, computers or other media, any data (“Excluded Data”) regulated pursuant to any law, rule, order or regulation of any governmental entity having jurisdiction over such data (collectively, the &quot;Excluded Data Laws&quot;). CUSTOMER RECOGNIZES AND AGREES THAT: (a) Hobo Fly Fishing HAS NO LIABILITY FOR ANY FAILURE TO PROVIDE PROTECTIONS SET FORTH IN THE EXCLUDED DATA LAWS OR OTHERWISE TO PROTECT EXCLUDED DATA; AND (b) Hobo Fly Fishing's SYSTEMS ARE NOT INTENDED FOR MANAGEMENT OR PROTECTION OF EXCLUDED DATA AND MAY NOT PROVIDE ADEQUATE OR LEGALLY REQUIRED SECURITY FOR EXCLUDED DATA.
            4.7. Aggregate &amp; Anonymized Data. Notwithstanding the provisions above of this Article 0, Hobo Fly Fishing may use, analyze, reproduce, sell, publicize, or otherwise exploit Aggregate Data in any way, in its sole discretion.  Further, Hobo Fly Fishing may share Aggregate Data with its vendors, service providers, subcontractors and business partners as it deems necessary or desirable including but not limited for purposes of providing the System and SaaS products and services to You and other parties.
            4.8. Audit.  Hobo Fly Fishing may audit your use of the System. You agree to cooperate with Hobo Fly Fishing’s audit and provide reasonable assistance and access to information.  Any such audit shall not unreasonably interfere with Your use of the System.        </p>
        <ol start="5">
            <li>
                <p>CUSTOMER’S RESPONSIBILITIES &amp; RESTRICTIONS.
                    5.1. Acceptable Use. You shall comply with the AUP, as the same is subject to change from time to time. You shall not: (a) use the System for service bureau or time-sharing purposes or in any other way allow third parties to exploit the System; (b) provide System passwords or other log-in or authorization information to any third party; or (c) access the System in order to build a competitive product or service, to build a product using similar ideas, features, functions or graphics of the System, or to copy any ideas, features, functions or graphics of the System. In the event that it suspects any breach of the requirements of this Section 5.1, including without limitation by Users, Hobo Fly Fishing may suspend Your access to the System without advanced notice, in addition to such other remedies as Hobo Fly Fishing may have. Neither this Agreement nor the AUP requires that Hobo Fly Fishing take any action against Customer or any User or other third party for violating the AUP, this Section 5.1, or this Agreement, but Hobo Fly Fishing is free to take any such action it sees fit.
                    5.2. Prohibited Use.  You agree not to use or permit use of the System, including by uploading,  emailing, posting, publishing or otherwise transmitting any material, for any purpose that may (a) menace or harass any person or cause damage or injury to any person or property, (b) involve the publication of any material that is false, defamatory, harassing or obscene, (c) violate privacy rights or promote bigotry, racism, hatred or harm , (d) constitute unsolicited bulk e-mail, “junk mail”, “spam” or chain letters; (e) constitute an infringement of intellectual property or other proprietary rights, or (f) otherwise violate applicable laws, ordinances or regulations. In addition to any other rights afforded to Hobo Fly Fishing under this Agreement, Hobo Fly Fishing reserves the right to remove or disable access to any material that violates the foregoing restrictions. Hobo Fly Fishing shall have no liability to you in the event that Hobo Fly Fishing takes such action. You agree to defend and indemnify Hobo Fly Fishing against any claim arising out of a violation of your obligations under this section.
                    5.3. Unauthorized Access. You shall take reasonable steps to prevent unauthorized access to the System, including without limitation by protecting passwords and other log-in information. You shall notify Hobo Fly Fishing immediately of any known or suspected unauthorized use of the System or breach of its security and shall use best efforts to stop said breach.
                    5.4. Compliance with Laws. When using the System, You shall comply with all applicable laws, including without limitation laws governing the protection of personally identifiable information and other laws applicable to the protection of Customer Data.
                    5.5. Your purchase of access to any SaaS product is for Your personal use only. Use of any SaaS product for commercial and/or institutional research purposes in any manner is specifically prohibited. If You wish to use a SaaS product for commercial or institutional research purposes or any purpose other than Your personal use, You must obtain the written consent of Hobo Fly Fishing and pay any and all applicable fee(s) for such use.
                    5.6. Users &amp; System Access. You are responsible and liable for: (a) Your use of the System, including without limitation unauthorized conduct and any conduct that would violate the AUP or the requirements of this Agreement applicable to You; and (b) any use of the System through Your  account or pursuant to an Order made by You, whether authorized or unauthorized.</p>
            </li>
            <li>
                <p>INTELLECTUAL PROPERTY (“IP”) RIGHTS AND CUSTOMER FEEDBACK.
                    6.1. IP Rights to the System. Hobo Fly Fishing retains at all times all right, title, and interest in and to the System, including without limitation all software used to provide the System and all graphics, user interfaces, logos, and trademarks reproduced through the System. This Agreement does not grant You any intellectual property license or rights in or to the System or any of its components. Customer recognizes that the System and its components are protected by copyright and other laws and shall at all times comply with the same.
                    6.2. Feedback. Hobo Fly Fishing has not agreed to and does not agree to treat as confidential any Feedback  You provide to Hobo Fly Fishing.  All Feedback provided to Hobo Fly Fishing, in any medium shall be deemed to be free of all copyright and/or other rights which are vested or may become vested in the Customer which provided such Feedback and may be utilized by Hobo Fly Fishing as it desires without payment or compensation of any kind. Nothing in this Agreement or in the parties’ dealings arising out of or related to this Agreement will restrict Hobo Fly Fishing’s right to use, profit from, disclose, publish, keep secret, or otherwise exploit Feedback, without compensating or crediting the Customer.</p>
            </li>
            <li>
                <p>CONFIDENTIAL INFORMATION. Confidential Information refers to the following items Hobo Fly Fishing discloses or makes available to You: (a) any document Hobo Fly Fishing marks “Confidential”; (b) any information Hobo Fly Fishing orally designates as “Confidential” at the time of disclosure, provided Hobo Fly Fishing confirms such designation in writing within ten (10) business days; (c) the Documentation, whether or not marked or designated confidential; and (d) any other nonpublic, sensitive information disclosed by Hobo Fly Fishing, whether or not marked or designated “Confidential.” Notwithstanding the foregoing, Confidential Information does not include information that: (i) is in Your possession at the time of disclosure; (ii) is independently developed by You without use of or reference to Confidential Information; (iii) becomes known publicly, before or after disclosure, other than as a result of Your improper action or inaction; or (iv) is approved for release in writing by Hobo Fly Fishing.
                    7.1. Nondisclosure. You shall not disclose Confidential Information to any other third party without Hobo Fly Fishing’s prior written consent. Without limiting the generality of the foregoing, You shall protect Confidential Information with reasonable care. You shall promptly notify Hobo Fly Fishing of any misuse or misappropriation of Confidential Information that comes to Your attention. Notwithstanding the foregoing, You may disclose Confidential Information as required by applicable law or by proper legal or governmental authority. You shall give Hobo Fly Fishing prompt notice of any such legal or governmental demand and reasonably cooperate with Hobo Fly Fishing in any effort to seek a protective order or otherwise to contest such required disclosure, at Hobo Fly Fishing’s expense.
                    7.2. Injunction. You agree that breach of this Article 7 would cause Hobo Fly Fishing irreparable injury, for which monetary damages would not provide adequate compensation, and that in addition to any other remedy, Hobo Fly Fishing will be entitled to injunctive relief against such breach or threatened breach, without proving actual damage or posting a bond or other security.
                    7.3. Retention of Rights. This Agreement does not transfer ownership of Confidential Information or grant a license or any rights thereto to You. Hobo Fly Fishing retains all right, title, and interest in and to all Confidential Information.</p>
            </li>
            <li>REPRESENTATIONS &amp; WARRANTIES.
                8.1. From Hobo Fly Fishing. Hobo Fly Fishing represents and warrants that it is the owner of the System and of each and every component thereof, or the recipient of a valid license or other agreement with respect thereto (e.g. a service provider/vendor agreement), and that it has and will maintain the full power and authority to grant the rights granted in this Agreement without the further consent of any third party. Hobo Fly Fishing’s representations and warranties in the preceding sentence do not apply to use of the System in combination with hardware or software not provided by Hobo Fly Fishing. In the event of a breach of the warranty in this Section 8.1, Hobo Fly Fishing, at its own expense, may take the following actions: (a) secure for You the right to continue using the System; (b) replace or modify the System to make it noninfringing; or (c) terminate the infringing features of the Service. In conjunction with Your right to terminate this Agreement for breach where applicable, the preceding sentence states Hobo Fly Fishing’s sole obligation and liability, and Your sole remedy, for breach of the warranty in this Section 8.1 and for potential or actual intellectual property infringement by the System.
                8.2. From Customer. You represent and warrants that: (a) You have the full right and authority to enter into, execute, and perform its obligations under this Agreement; (b) You have accurately identified Yourself and You have not provided any inaccurate information about Yourself to or through the System; and (c) You are a person aged 18 or older, a corporation, the sole proprietorship of an individual 18 years or older, or another entity authorized to do business pursuant to applicable law.
                8.3. Warranty Disclaimers. YOU ACCEPT THE SYSTEM “AS IS” AND AS AVAILABLE, WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS, OR ANY IMPLIED WARRANTY ARISING FROM STATUTE, COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING: (a) Hobo Fly Fishing HAS NO OBLIGATION TO INDEMNIFY OR DEFEND YOU AGAINST CLAIMS RELATED TO INFRINGEMENT OF INTELLECTUAL PROPERTY; (b) Hobo Fly Fishing DOES NOT REPRESENT OR WARRANT THAT THE SYSTEM WILL PERFORM WITHOUT INTERRUPTION OR ERROR; AND (c) Hobo Fly Fishing DOES NOT REPRESENT OR WARRANT THAT THE SYSTEM IS SECURE FROM HACKING OR OTHER UNAUTHORIZED INTRUSION OR THAT CUSTOMER DATA WILL REMAIN PRIVATE OR SECURE.</li>
        </ol>
        <p>Hobo Fly Fishing DOES NOT GUARANTEE THAT THE SAAS PRODUCTS WILL BE PROVIDED ERROR-FREE OR UNINTERRUPTED, OR THAT Hobo Fly Fishing WILL CORRECT ALL ERRORS. YOU ACKNOWLEDGE THAT Hobo Fly Fishing DOES NOT CONTROL THE TRANSFER OF DATA OVER COMMUNICATIONS FACILITIES, INCLUDING THE INTERNET, AND THAT THE SYSTEM MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS  INHERENT IN THE USE OF SUCH COMMUNICATIONS FACILITIES. Hobo Fly Fishing IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS WHETHER OR NOT FORESEEABLE.</p>
        <p>THERE IS NO GUARANTEE OR PROMISE THAT YOUR USE OF THE SYSTEM WILL ENABLE OR ASSIST YOU IN WINNING MONEY, OR THAT YOU WILL NOT LOSE MONEY, OR IMPROVE YOUR GAMING RESULTS. YOUR RESULTS WILL VARY AND WILL BE BASED ON YOUR ABILITIES, EXPERIENCE, KNOWLEDGE, CAPABILITIES, LEVEL OF DESIRE, AND AN INFINITE NUMBER OF VARIABLES BEYOND Hobo Fly Fishing's CONTROL, INCLUDING VARIABLES Hobo Fly Fishing AND YOU HAVE NOT ANTICIPATED. EACH CUSTOMER’S RESULTS WILL VARY.</p>
        <p>TO THE EXTENT NOT PROHIBITED BY LAW, THESE WARRANTIES ARE EXCLUSIVE AND THERE ARE NO OTHER EXPRESS OR IMPLIED WARRANTIES OR CONDITIONS .</p>
        <ol start="9">
            <li>
                <p>INDEMNIFICATION. You shall defend, indemnify, and hold harmless Hobo Fly Fishing and the Hobo Fly Fishing Associates  against any “Indemnified Claim,” meaning any third party claim, suit, or proceeding arising out of or related to Yours alleged or actual use of, misuse of, or failure to use the System, including without limitation: (a) claims related to unauthorized disclosure or exposure of personally identifiable information or other private information, including Customer Data; (b) claims related to infringement or violation of a copyright, trademark, trade secret, or privacy or confidentiality right by written material, images, logos or other content uploaded to the System through Your account, including without limitation by Customer Data; and (c) claims that use of the System through Your  account harasses, defames, or defrauds a third party or violates the CAN-Spam Act of 2003 or any other law or restriction on electronic advertising. Indemnified Claims include, without limitation, claims arising out of or related to Hobo Fly Fishing’s negligence. Your obligations set forth in this Article 9 include retention and payment of attorneys and payment of court costs, as well as settlement at Your expense and payment of judgments. Hobo Fly Fishing will have the right, not to be exercised unreasonably, to reject any settlement or compromise that requires that it admit wrongdoing or liability or subjects it to any ongoing affirmative obligations.</p>
            </li>
            <li>
                <p>LIMITATION OF LIABILITY.
                    10.1. Liquidated Damages. YOU SPECIFICALLY AGREE THAT THE LIMIT OF Hobo Fly Fishing's LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT AND ITS OBLIGATIONS HEREIN WILL NOT EXCEED THE GREATER OF YOUR COST TO ACCESS THE SYSTEM FOR A ONE (1) MONTH PERIOD OR FIFTY DOLLARS ($50).
                    10.2. Exclusion of Consequential Damages. IN NO EVENT WILL Hobo Fly Fishing BE LIABLE TO YOU FOR ANY CONSEQUENTIAL, INDIRECT, SPECIAL, INCIDENTAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO THIS AGREEMENT WHETHER OR NOT SUCH DAMAGES WERE FORSEEABLE.
                    10.3. Clarifications &amp; Disclaimers. THE LIABILITIES LIMITED BY THIS ARTICLE 10 APPLY:
                    (a) TO LIABILITY FOR NEGLIGENCE;
                    (b) REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, STRICT PRODUCT LIABILITY, OR OTHERWISE;
                    (c) EVEN IF Hobo Fly Fishing IS ADVISED IN ADVANCE OF THE POSSIBILITY OF THE DAMAGES IN QUESTION AND EVEN IF SUCH DAMAGES WERE FORESEEABLE; AND
                    (d) EVEN IF YOUR REMEDIES FAIL OF THEIR ESSENTIAL PURPOSE.
                    If applicable law limits the application of the provisions of this Article 10, Hobo Fly Fishing’s liability will be limited to the maximum extent permissible. For the avoidance of doubt, Hobo Fly Fishing’s liability limits and other rights set forth in this Article 10 apply likewise to Hobo Fly Fishing Associates, Hobo Fly Fishing’s affiliates, licensors, suppliers, advertisers, agents, sponsors, directors, officers, employees, consultants, and other representatives.</p>
            </li>
            <li>
                <p>Term &amp; Termination.
                    11.1. Termination for Cause. Either party may terminate this Agreement for the other’s material breach by written notice, effective in thirty (30) days unless the other party first cures such breach.
                    11.2. Effects of Termination. Upon termination of this Agreement, You shall cease all use of the System and delete, destroy, or return all copies of the Documentation in Your possession or control. The following provisions will survive termination or expiration of this Agreement: (a) any obligation of You to pay fees incurred before termination; (b) Articles and Sections 6 (IP and Feedback), 7 (Confidential Information), 8.3 (Warranty Disclaimers), 9 (Indemnification), and 10 (Limitation of Liability); and (c) any other provision of this Agreement that must survive to fulfill its essential purpose.</p>
            </li>
            <li>
                <p>ENTIRE AGREEMENT. You agree that this Agreement (including the information which is incorporated into this Agreement by reference (including reference to information contained in a URL or a referenced policy), is the complete agreement for the SaaS products and access to the System ordered by You, and that this  Agreement supersedes all prior or contemporaneous agreements or representations, written or oral, regarding such products. If any term of this Agreement is found to be invalid or unenforceable, the remaining provisions will remain effective and such term shall be replaced with a term consistent with the purpose and intent of this Agreement. It is expressly agreed that the terms of this Agreement, including any Hobo Fly Fishing ordering document, shall supersede the terms in any purchase order or other non-Hobo Fly Fishing document and no terms included in any such purchase order or other non-Hobo Fly Fishing document shall apply to the SaaS products ordered. This Agreement may not be modified and the rights and restrictions may not be altered or waived except in a writing signed or accepted online through a Hobo Fly Fishing website by authorized representatives of You and of Hobo Fly Fishing.</p>
            </li>
            <li>MISCELLANEOUS.
                13.1. Independent Contractors. The parties are independent contractors and will so represent themselves in all regards. Neither party is the agent of the other, and neither may make commitments on the other’s behalf.
                13.2. Notices. Hobo Fly Fishing may send notices pursuant to this Agreement to You at the email contact points provided by You, and such notices will be deemed received twenty four (24) hours after they are sent. You may send notices pursuant to this Agreement to Hobo Fly Fishing at agreement (at) maxvaluesoftware.com , and such notices will be deemed received twenty four (24) hours after they are sent.
                13.3. Force Majeure. No delay, failure, or default, other than a failure to pay fees when due, will constitute a breach of this Agreement to the extent caused by acts of war, terrorism, hurricanes, earthquakes, other acts of God or of nature, strikes or other labor disputes, riots or other acts of civil disorder, embargoes, or other causes beyond the performing party’s reasonable control.
                13.4. Assignment &amp; Successors. You may not assign this Agreement or any of its rights or obligations hereunder without Hobo Fly Fishing’s express written consent. Except to the extent forbidden in this Section 13.4, this Agreement will be binding upon and inure to the benefit of the parties’ respective successors and assigns.
                13.5. Severability. To the extent permitted by applicable law, the parties hereby waive any provision of law that would render any clause of this Agreement invalid or otherwise unenforceable in any respect. In the event that a provision of this Agreement is held to be invalid or otherwise unenforceable, such provision will be interpreted to fulfill its intended purpose to the maximum extent permitted by applicable law, and the remaining provisions of this Agreement will continue in full force and effect.
                13.6. No Waiver. Neither party will be deemed to have waived any of its rights under this Agreement by lapse of time or by any statement or representation other than by an authorized representative in an explicit written waiver. No waiver of a breach of this Agreement will constitute a waiver of any other breach of this Agreement.
                13.7. Choice of Law &amp; Jurisdiction: This Agreement will be governed solely by the internal laws of the State of Delaware, United States of America, without reference to: (a) any conflicts of law principle that would apply the substantive laws of another jurisdiction to the parties’ rights or duties; (b) the 1980 United Nations Convention on Contracts for the International Sale of Goods; or (c) other international laws. The parties consent to the personal and exclusive jurisdiction of the federal and state courts of New Castle County, Delaware.
                13.8. Conflicts. In the event of any conflict between this Agreement and any Hobo Fly Fishing policy posted online, including without limitation the AUP or Privacy Policy, the terms of this Agreement will govern.
                13.9. Construction. The parties agree that the terms of this Agreement result from negotiations between them. This Agreement will not be construed in favor of or against either party by reason of authorship.
                13.10. Technology Export. You shall not: (a) permit any third party to access or use the System in violation of any U.S. law or regulation; or (b) export any software provided by Hobo Fly Fishing or otherwise remove it from the United States except in compliance with all applicable U.S. laws and regulations. Without limiting the generality of the foregoing, You shall not permit any third party to access or use the System in, or export such software to, a country subject to a United States embargo (including, as of the Effective Date, Iran, North Korea, Sudan, and Syria). You agree that no data, information, software programs and/or materials resulting from Your use of the System (or direct product thereof) will be exported, directly or indirectly, in violation of these laws. You may visit the U.S. Department of Treasury website located at <a href="http://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx">http://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx</a>) for more information.
                13.11. Entire Agreement. This Agreement sets forth the entire agreement of the parties and supersedes all prior or contemporaneous writings, negotiations, and discussions with respect to its subject matter. Neither party has relied upon any such prior or contemporaneous communications.
                13.12. Amendment. Hobo Fly Fishing may amend this Agreement from time to time by posting an amended version on the website at which access to the System may be ordered. As a condition of this Agreement, you agree to periodically check the posted version of this Agreement. You agree that your continued use of the System after the date this Agreement has been amended will constitute your consent and acceptance of the Agreement as amended. This Agreement may not be amended in any other way except through a written agreement by authorized representatives of each party. Notwithstanding the foregoing provisions of this Section 13.12, Hobo Fly Fishing may revise its privacy policies and AUP at any time by posting a new version of either at Hobo Fly Fishing’s websites, and such new version will become effective on the date it is posted.</li>
        </ol>
    </div>
@stop
