# Hobo Fly Fishing CI and CD brought to you by CircleCI, Slack, Envoyer.io and my personal lack of awesomeness.
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.8-browsers
      - image: circleci/node:4.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Download NodeJS v6
          command: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - run:
          name: Install Nodejs 6
          command: sudo apt-get install -y nodejs
      - run: sudo apt install -y libsqlite3-dev
      - run: sudo apt-get install -y libpng-dev
      - run: sudo apt-get install -y libmagickwand-dev
      - run: sudo pecl install imagick-3.4.3 && sudo docker-php-ext-enable imagick
      - run:
          name: Install PHP GD Extension
          command: sudo docker-php-ext-install gd
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          - v1-dependencies-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Install NodeJS Packages
          command: npm install
      - run: cp .env.example .env
      - run: composer install -n --ignore-platform-reqs
      - run: npm run production
      - run: touch storage/testing.sqlite
      - run: php artisan key:generate
      - run: php artisan migrate
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      # run tests!
      - run:
         name: Start Chrome Driver
         command: ./vendor/laravel/dusk/bin/chromedriver-linux
         background: true
      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true
      - run:
         name: Run Laravel Dusk Tests
         command: php artisan dusk
      - run: php artisan dusk
notify:
  webhooks:
    # A list of hook hashes, containing the URL field
    - url: https://hoboflyfishing.com/deploy-HfDamFwqhXEUUsHg6t4L
